Fixed the NoSuchMethodError about the missing static interface sendPackageBroadcast and init for the PackageManagerService.java by overloading the interface